# Generated by Django 4.2.7 on 2024-01-15 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_changed',
        ),
    ]
