# Generated by Django 4.2.7 on 2024-01-15 02:46

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_password_changed'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authentication.models.CustomUserManager()),
            ],
        ),
    ]
