# Generated by Django 4.2.7 on 2024-01-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
