# Generated by Django 4.2.7 on 2024-01-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_management', '0002_alter_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PlantOrder',
        ),
    ]
