# Generated by Django 4.2.7 on 2024-01-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_management', '0004_imagecategory_image_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagecategory',
            options={'verbose_name': 'ImageCategory', 'verbose_name_plural': 'ImageCategories'},
        ),
    ]
