# Generated by Django 4.2.7 on 2024-01-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_management', '0005_alter_imagecategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedurl',
            name='name',
            field=models.CharField(default='wiki', max_length=2047),
            preserve_default=False,
        ),
    ]
